name = "Re-Console"
author = "omo50"
version = "2.2.0+mc1.21.5+fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4eae741d07a58ec791b8540014f53dd3040ee98a6c32f3c8504054d0151bb538"

[versions]
fabric = "0.16.14"
minecraft = "1.21.5"
