name = "Re-Console Special Edition"
author = "omo50"
version = "13.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c9f8a919df51c7652e2eebd641140631f19d55ea4a96dc1ebcbe7282570829cc"

[versions]
fabric = "0.16.14"
minecraft = "1.21.5"
