name = "Re-Console"
author = "omo50"
version = "2.2.0+mc1.21.4+fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b965a887f373992c54ac278a30e6a030adda1b46644737ae7e6c007c1c40b8d7"

[versions]
fabric = "0.16.14"
minecraft = "1.21.4"
