name = "Re-Console"
author = "omo50"
version = "2.2.0+mc1.21.1+neoforged"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "021ec953a4ce860ea9588f41f86a759eb3ed85ae644597e06ad771ff427a9c72"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.174"
