name = "Re-Console"
author = "omo50"
version = "2.2.0+mc1.21.5+neoforged"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "27739ac91ef74ebb9d9a36ba67701dfedddbac9420f4ecb4a3c882a591b36141"

[versions]
minecraft = "1.21.5"
neoforge = "21.1.174"
